%% Import the log from new logger
% This version of the log is generated by using the logger written by
% software group to log only the four arm pose (quaternion). All the pose
% are registered to the camera frame. The raw data are saved in
% 'sytlus_sponge.mat'. Run the script 'ImportSpongeStylusToolPath.m'
% after this to generate the tool path. The original log comes from google
% drive:
% https://drive.google.com/a/verbsurgical.com/file/d/0B9foQKIt64-6eVJWUVkzUzZWZ3M/view?ts=5716b939
%%

% clc
% clear all
% filename = 'C:\Users\MATLAB\Desktop\logs\egg_sponge_user04.txt';
data = importdata(filename);
num_samples = (length(data.data) - 4 )/4;
time_stamp = zeros(num_samples,1);
arm0 = zeros(num_samples,7);
arm1 = zeros(num_samples,7);
arm2 = zeros(num_samples,7);
arm3 = zeros(num_samples,7);
gripper0 = zeros(num_samples,2);
gripper1 = zeros(num_samples,2);
gripper2 = zeros(num_samples,2);
gripper3 = zeros(num_samples,2);
for index = 1:num_samples
time_stamp(index) = data.data((index*4-3) + 3,1);
arm0(index,:) = data.data((index*4-3) + 3,2:8);
arm1(index,:) = data.data((index*4-2) + 3,2:8);
arm2(index,:) = data.data((index*4-1) + 3,2:8);
arm3(index,:) = data.data((index*4-0) + 3,2:8);
gripper0(index,:) = data.data((index*4-3) + 3,9:10);
gripper1(index,:) = data.data((index*4-2) + 3,9:10);
gripper2(index,:) = data.data((index*4-1) + 3,9:10);
gripper3(index,:) = data.data((index*4-0) + 3,9:10);
end
% save('export/sytlus_sponge_2016_5_6.mat','time_stamp','arm0','arm1','arm2','arm3','gripper0','gripper1','gripper2','gripper3')