function necessity2015armupdated = importSTLfilesfromURDF(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   NECESSITY2015ARMUPDATED = IMPORTFILE(FILENAME) Reads data from text
%   file FILENAME for the default selection.
%
%   NECESSITY2015ARMUPDATED = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads
%   data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   necessity2015armupdated = importfile('necessity_2015_arm_updated.urdf.xacro', [34,70,121,172,223,274,326,377,428,483,538,589,640,691,742,793], [34,70,121,172,223,274,326,377,428,483,538,589,640,691,742,793]);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/06/25 14:34:40

%% Initialize variables.
delimiter = ' ';
if nargin<=2
    startRow = [34,70,121,172,223,274,326,377,428,483,538,589,640,691,742,793];
    endRow = [34,70,121,172,223,274,326,377,428,483,538,589,640,691,742,793];
end

%% Format string for each line of text:
%   column1: text (%q)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%*s%*s%*s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow(1)-1, 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    textscan(fileID, '%[^\n\r]', startRow(block)-1, 'ReturnOnError', false);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'ReturnOnError', false);
    dataArray{1} = [dataArray{1};dataArrayBlock{1}];
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
necessity2015armupdated = [dataArray{1:end-1}];
